"""0006_create_auth_billing_tables

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-03 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False, server_default="free"),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prefix", sa.String(length=10), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_prefix"), "api_keys", ["prefix"])

    op.create_table(
        "usage_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id"), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usage_records_workspace_id"), "usage_records", ["workspace_id"])
    op.create_index(op.f("ix_usage_records_recorded_at"), "usage_records", ["recorded_at"])

    op.create_table(
        "workspace_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id"), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False, server_default="member"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add columns to existing users table
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("display_name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"))
    op.add_column("users", sa.Column("active_workspace_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # Add workspace_id to projects table
    op.add_column("projects", sa.Column("workspace_id", sa.Integer(), sa.ForeignKey("workspaces.id"), nullable=True))
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"])

    # Seed a default admin user + workspace
    op.execute("""
        INSERT INTO users (id, email, password_hash, display_name, is_active, created_at, updated_at)
        VALUES (1, 'admin@dataproof.local',
                '$argon2id$v=19$m=65536,t=3,p=4$placeholder',
                'Admin', true, NOW(), NOW())
        ON CONFLICT (id) DO UPDATE
            SET password_hash = EXCLUDED.password_hash,
                display_name = EXCLUDED.display_name,
                is_active = EXCLUDED.is_active
    """)
    op.execute("""
        INSERT INTO workspaces (id, name, slug, plan, created_at, updated_at)
        VALUES (1, 'Default Workspace', 'default', 'pro', NOW(), NOW())
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        UPDATE users
        SET active_workspace_id = 1
        WHERE id = 1 AND active_workspace_id IS NULL
    """)
    op.execute("""
        INSERT INTO workspace_memberships (user_id, workspace_id, role, created_at)
        VALUES (1, 1, 'owner', NOW())
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        UPDATE projects
        SET workspace_id = 1
        WHERE workspace_id IS NULL
    """)

    # Make workspace_id NOT NULL after migration
    op.alter_column("projects", "workspace_id", nullable=False)

    # Make password_hash NOT NULL after migration
    op.alter_column("users", "password_hash", nullable=False)

    # Advance sequences past manually inserted IDs
    op.execute("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users))")
    op.execute("SELECT setval('workspaces_id_seq', (SELECT MAX(id) FROM workspaces))")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_memberships")
    op.drop_index(op.f("ix_usage_records_recorded_at"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_workspace_id"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_api_keys_prefix"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_table("workspaces")

    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "active_workspace_id")
    op.drop_column("users", "is_active")
    op.drop_column("users", "display_name")
    op.drop_column("users", "password_hash")

    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_column("projects", "workspace_id")
    # ### end Alembic commands ###
